# permissions for end users to edit fmapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fmapp-editor-role
rules:
- apiGroups:
  - apps.dev.quack.dev
  resources:
  - fmapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.dev.quack.dev
  resources:
  - fmapps/status
  verbs:
  - get
