# permissions for end users to view fmapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fmapp-viewer-role
rules:
- apiGroups:
  - apps.dev.quack.dev
  resources:
  - fmapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.dev.quack.dev
  resources:
  - fmapps/status
  verbs:
  - get
